apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-demo
  template:
    metadata:
      labels:
        app: user-demo
    spec:
      containers:
      - name: user-demo
        image: 103109354572.dkr.ecr.eu-west-2.amazonaws.com/user-demo:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/userdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpassword
