spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      search:
        default:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
jwt:
  secret: myJwtSecretIsThis
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"
